name: Ren'Py-py3_12-windows-x86_64

on:
  workflow_dispatch:
    branch: master

jobs:
  build:
    name: 编译构建
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: 检查代码
      uses: actions/checkout@v4

    - name: 安装 Python 3.12
      id: py
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: 安装 MSYS2 编译工具链及 C 库
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-sdl3
          mingw-w64-ucrt-x86_64-sdl3-image
          mingw-w64-ucrt-x86_64-sdl3-ttf
          mingw-w64-ucrt-x86_64-ffmpeg
          mingw-w64-ucrt-x86_64-freetype
          mingw-w64-ucrt-x86_64-harfbuzz
          mingw-w64-ucrt-x86_64-fribidi
          mingw-w64-ucrt-x86_64-assimp
          mingw-w64-ucrt-x86_64-openssl
          mingw-w64-ucrt-x86_64-libjpeg-turbo
          mingw-w64-ucrt-x86_64-pkgconf

    - name: 修补源文件兼容问题
      run: |
        # UTF-8 编码
        sed -i 's/with open(fn) as f:/with open(fn, encoding="utf-8") as f:/' scripts/setuplib.py
        # .pyd 没有 main，告诉 SDL 别找 SDL_main
        sed -i 's/setuplib.extra_compile_args = \["-Wno-unused-function"\]/setuplib.extra_compile_args = ["-Wno-unused-function", "-DSDL_MAIN_HANDLED"]/' setup.py

    - name: 安装 Python 模块
      run: |
        export PY="$(cygpath -u '${{ steps.py.outputs.python-path }}')"
        export PYDIR="$(dirname "$PY")"
        export PATH="$PYDIR:$PYDIR/Scripts:$PATH"
        python -m pip install setuptools cython future six typing pefile requests assimp legacy-cgi pkgconfig chardet websockets pysocks jinja2 rsa

    - name: 编译renpy运行所需模块
      run: |
        export PY="$(cygpath -u '${{ steps.py.outputs.python-path }}')"
        export PYDIR="$(dirname "$PY")"
        export PATH="$PYDIR:$PYDIR/Scripts:$PATH"
        export RENPY_CYTHON=cython
        export CPUS=$(nproc)
        python setup.py build_ext --compiler=mingw32 -b tmp/build/lib.renpy-run -t tmp/build/tmp.renpy-run --inplace -j $CPUS

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: renpy-py3_12-windows-x86_64
        path: ./
